services:
  l-town:
    image: ghcr.io/besoeasy/l-town:latest
    container_name: l-town
    labels:
      yantr.app: "l-town"
      yantr.service: "Game UI"
    ports:
      - "30300"
    restart: unless-stopped
